### ISSUE TITLE
More flags for suspicious iD edits

### ISSUE THREAD

**Issue by bhousel** [willemarcel/osmcha#14]
To catch importers or people with iD forks doing suspicious things, osmcha could add rules for:

- iD version not current
- iD host not openstreetmap.org

These things can be checked from changeset tags:

<img width="300" alt="screenshot 2017-02-17 23 04 31" src="https://cloud.githubusercontent.com/assets/38784/23090181/810a363c-f565-11e6-8a0d-da919e772ddc.png">

**Comment by willemarcel** [comment]
Good suggestion, @bhousel! I'll do it soon.

**Comment by willemarcel** [comment]
@bhousel `osmcha` now verifies the host field of iD edits (https://github.com/willemarcel/osmcha/commit/5ab652c11e2806ac15079f693b9ad59ee15ef747). Furthermore osm.org website, I added Strava and ImproveOSM as trusted instances. Do you know some other instances?

As each time a changeset receives a new comment it comes again in the changeset replication feed, it's common to have old changesets being analysed. So checking the version would return some false positives.

**Comment by bhousel** [comment]
> @bhousel, osmcha now verifies the host field of iD edits (5ab652c). Furthermore osm.org website, I added Strava and ImproveOSM as trusted instances. Do you know some other instance?

Thanks!  I don't know of any others in widespread use..
