### ISSUE TITLE
osmcha doesn't handle changesets with no tags at all

### ISSUE THREAD

**Issue by bhousel** [willemarcel/osmcha#15]
I accidentally created this changeset with no tags at all.  whoops!
http://www.openstreetmap.org/changeset/46755934

It seems invisible to osmcha, this just returns "Page Not Found"
http://osmcha.mapbox.com/46755934/

**Comment by willemarcel** [comment]
Thank you, @bhousel! I didn't imagine that it is possible to create a changeset with no tag. Solved in https://github.com/willemarcel/osmcha/commit/6dc01ea3bfac664ac8fcf9eb934c75753bf61d3a
