### ISSUE TITLE
suspect_word false positive

### ISSUE THREAD

**Issue by marcioaguiar** [willemarcel/osmcha#2]
[This changeset](http://www.openstreetmap.org/changeset/36707110) has generated a false positive  _suspect_word_, possibly due to the word "**import**ante".

A solution would be checking for a blank space, punctuation or end of line after suspect words.

[1] http://www.openstreetmap.org/changeset/36707110

**Comment by willemarcel** [comment]
@marcioaguiar added `importante` as an excluded word of the analysis. https://github.com/willemarcel/osmcha/commit/122a9272d4b1959ffc66710f6fceca5ac2719fb4
