### ISSUE TITLE
Why is this flagged with Suspect Word?

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha#20]
http://osmcha.mapbox.com/47314376/

@willemarcel - any idea?

**Comment by willemarcel** [comment]
@batpad "fix" is in the list of suspect words. I thinks it's better to remove it, a search for fix returned more than 100000 results in osmcha

**Comment by willemarcel** [comment]
done in https://github.com/willemarcel/osmcha/commit/6b33dd81fc35b0d4c497c7ae2964d2d35cb1a72c
