### ISSUE TITLE
Don't add unrequested pointless messages

### ISSUE THREAD

**Issue by SomeoneElseOSM** [willemarcel/osmcha#29]
For example, https://www.openstreetmap.org/changeset/55562596#map=4/51.26/14.55 is a case in point.

No review was requested.

The changeset author knew exactly what they were doing.

There's nothing wrong with someone saying in their own words something to the effect of "thanks for that" in a changeset discussion comment (I've done it myself many times) but please not an automatically generated comment that looks like it was written by a 6-year old (and that's not hyperbole - adults tend not to complete every sentence with an exclamation mark).  It just looks rude.

**Comment by willemarcel** [comment]
Hi @SomeoneElseOSM 

Sorry for the problem. We are working to solve it. In some days a new version will be released with the fix.

Thank you very much for your feedback!

**Comment by willemarcel** [comment]
Solved some months ago
