### ISSUE TITLE
Suspect word `here` is too common and gives false positive

### ISSUE THREAD

**Issue by maning** [willemarcel/osmcha#3]
See for example this changeset: http://www.openstreetmap.org/changeset/36776280.
It was flagged as suspect word because the source mentioned the [word "here"](https://github.com/willemarcel/osmcha/blob/master/osmcha/changeset.py#L151).  We know that HERE is a mapping brand but the word is too common.

**Comment by alexandre-mbm** [comment]
Distinguish the case? `H(e|E)(r|R)(e|E) ~ h(e|E)(r|R)(e|E)`? I think be better let it as is...

**Comment by willemarcel** [comment]
Hi @maning 

In the last 30 days, there are 287 changesets containing ' here' (http://resultmaps.neis-one.org/osm-changesets?comment=%20here#2/11.7/11.3). I think we really should remove it from the suspect words.

**Comment by alexandre-mbm** [comment]
Maybe using regex false positives would be less.

**Comment by willemarcel** [comment]
'here' word was removed
