### ISSUE TITLE
Cannot comment verified changesets

### ISSUE THREAD

**Issue by Nakaner** [willemarcel/osmcha#34]
> It was not possible to post your comment.

I have been getting this error for all changesets I marked as "bad" when I wanted to post a changeset comment through OSMCha. I am logged in and clicked on "Verify" → "bad" beforehand. The changesets to be commented are closed.

**Comment by willemarcel** [comment]
@Nakaner Thanks for the report. I have noticed the comments are failing if it contains special characters. I'm working to fix this right now.

**Comment by Nakaner** [comment]
My comments were in German and might have contained the umlauts ä, ö and ü.

**Comment by willemarcel** [comment]
Fixed with https://github.com/willemarcel/osmcha-django/pull/151. The new version will be running on Monday

**Comment by willemarcel** [comment]
@Nakaner We have deployed a new osmcha version with this issue fixed.
