### ISSUE TITLE
[premerge] Fix failing tests

### ISSUE THREAD

**Issue by bkowshik** [willemarcel/osmcha#7]
I ran the tests with the following steps.

```sh
# Setup a virtual environment to install required packages.
mkvirtualenv osmcha

# Install required packages in locally editable (``-e``) mode.
pip install -e .[test]

# Run the tests.
py.test
```

Not all tests passed and below is the test summary.
```sh
=== 4 failed, 11 passed in 115.73 seconds ===
```

cc: @willemarcel @batpad @amishas157

**Comment by willemarcel** [comment]
@bkowshik solved with https://github.com/willemarcel/osmcha/commit/11c5d27000854196ac2674e33f801ad909d4cb68

**Comment by bkowshik** [comment]
💥
